#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off # autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16

# yabai -m config external_bar all:20:0

yabai -m rule --add app="^Arc$" subrole='AXSystemDialog' manage=off mouse_follows_focus=off
yabai -m rule --add app="^Arc$" title="^$" manage=off mouse_follows_focus=off

killall borders; borders width=12.0 inactive_color=0xff43436C active_color=0xff6693BF &; disown;
